- hosts: master
  tasks:
    - name: create nexus docker secret
      community.kubernetes.helm:
        name: nexusdocker
        release_namespace: devops-tools
        chart_ref: nexus
        wait: true
