check that everything works with:

[source]
----
mvn test exec:java
----

The command compiles the project and runs the tests, then  it launches the application, so you can check by yourself. Open your browser to http://localhost:8080. You should see a _Hello World_ message.

== Anatomy of the project

The project contains:

* a `pom.xml` file
* a _main_ verticle file (src/main/java/io/vertx/starter/MainVerticle.java)
* an unit test (src/main/test/io/vertx/starter/MainVerticleTest.java)

Run `redeploy.sh` and the project recompiles while editing.

NOTE: the `redeploy` script are also configurable

== Building the project

To build the project, just use:

----
1. mvn clean package
----

It generates a _fat-jar_ in the `target` directory.

build and create docker image:

2. mvn clean install
pushed auch das image ins docker repo, weiter mit 6.

To compile, build, and push the image to a remote repo:
mvn clean deploy -Ddocker.user=<username> -Ddocker.password=<passwd> -Ddocker.url=<docker-registry-url>

?mvn clean deploy -Ddocker.user=admin -Ddocker.password=admin123 -Ddocker.url=http://10.211.55.4:32000/repository/docker-repo/
mvn clean deploy -Ddocker.user=admin -Ddocker.password=admin123 -Ddocker.url=http://10.211.55.4:32132

curl -v -u admin:admin123 --upload-file /Users/wewer/workspace/yuuvisvapi/target/yuuvis-v-api-1.2-SNAPSHOT.jar http://10.211.55.4:32000/repository/maven-snapshots/juergenwewer/optimal/yuuvis-v-api/1.2-SNAPSHOT/yuuvis-v-api-1.2-SNAPSHOT.jar

docker login http://10.211.55.4:32132
3. docker image ls

4. docker image tag e2faa1e00eaa 10.211.55.4:32132/yuuvis-v-api:1.1-SNAPSHOT
5. docker push 10.211.55.4:32132/yuuvis-v-api:1.1-SNAPSHOT

on the master node:

ssh root@10.211.55.4

(only mac:)
in: ~/.docker/daemon.json

debian:
/etc/docker/daemon.json

add:
{"insecure-registries":["10.211.55.4:32132"]}
on mac, desktop docker restart
on debian:
systemctl daemon-reload
systemctl restart docker
check with docker info:

docker login http://10.211.55.4:32132

cat ~/.docker/config.json

kubectl create secret generic regcred \
    --from-file=.dockerconfigjson=/root/.docker/config.json \
    --type=kubernetes.io/dockerconfigjson --dry-run=client  --output=yaml > jwt-secrets.yaml


create helm chart:

helm create nexus
die datei: jwt-secrets.yaml nach nexus/template kopieren

testlauf:
helm template --debug nexus

dann secret generieren:
helm install nexus --generate-name

6. edit the version in api.yaml
7. helm install api --generate-name
funtioniert nicht:
ansible-playbook -i macpro dockersecret.yaml  -v


total:

to build a new version:
edit version in pom
mvn clean package
edit the Dockerfile - put in the version
mvn clean install
edit the version in api helm - deployment.yaml in the image:
helm install api --generate-name
check the service yuuvis-api for the IP -> 30127
http://10.211.55.4:30127/ in the Browser

new:

edit version in pom
mvn clean install
edit the Dockerfile - put in the version
mvn clean deploy

docker secret:
helm install nexus --generate-name

edit the version in api helm - deployment.yaml in the image:
helm install yuuvis-v-api api

helm uninstall yuuvis-v-api
