apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyIxMC4yMTEuNTUuNDozMjEzMiI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbjEyMyIsImVtYWlsIjoianVlcmdlbi53ZXdlckBnbWFpbC5jb20iLCJhdXRoIjoiWVdSdGFXNDZZV1J0YVc0eE1qTT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
