apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxMC4yMTEuNTUuNDozMjEzMiI6IHsKCQkJImF1dGgiOiAiWVdSdGFXNDZZV1J0YVc0eE1qTT0iCgkJfQoJfQp9
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: yuuvis
type: kubernetes.io/dockerconfigjson

