apiVersion: v1
kind: ConfigMap
metadata:
  name: yuuvisapiconfigmap
  namespace: yuuvis
data:
  tenant: yuuvistest
  serverurl: '{{ .Values.serverurl }}{{ if .Values.serverport }}:{{ .Values.serverport }}{{ end }}'
