apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuuvis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuuvis-api
  template:
    metadata:
      labels:
        app: yuuvis-api
    spec:
      containers:
      - name: yuuvis-api
        image: 10.211.55.4:32132/yuuvis-v-api:1.3-SNAPSHOT
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
