apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuuvis-api
  namespace: yuuvis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuuvis-api
  template:
    metadata:
      labels:
        app: yuuvis-api
    spec:
      containers:
      - name: yuuvis-api
        image: jw-cloud.org:8443/yuuvis-v-api:2.0.1-SNAPSHOT
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: jwcloudcred
