apiVersion: v1
kind: Secret
metadata:
  name: yuuvissecret
  namespace: yuuvis
type: kubernetes.io/basic-auth
stringData:
  username: yuuvis
  password: optimalsystem
  yuuvisusername: root
  yuuvispassword: optimalsystem
