apiVersion: v1
kind: Service
metadata:
  name: yuuvis-api
  namespace: yuuvis
  labels:
    app: yuuvis-api
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: yuuvis-api
